/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ocacinternship.MiniProject;

import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class AttandanceCalculator extends javax.swing.JFrame {

    /**
     * Creates new form Attandance
     */
    public AttandanceCalculator() {
        initComponents();
          t1.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<>();
        s1 = new javax.swing.JCheckBox();
        s2 = new javax.swing.JCheckBox();
        s3 = new javax.swing.JCheckBox();
        s5 = new javax.swing.JCheckBox();
        s6 = new javax.swing.JCheckBox();
        s7 = new javax.swing.JCheckBox();
        s8 = new javax.swing.JCheckBox();
        s9 = new javax.swing.JCheckBox();
        s10 = new javax.swing.JCheckBox();
        s11 = new javax.swing.JCheckBox();
        s12 = new javax.swing.JCheckBox();
        s13 = new javax.swing.JCheckBox();
        s15 = new javax.swing.JCheckBox();
        s16 = new javax.swing.JCheckBox();
        s17 = new javax.swing.JCheckBox();
        s18 = new javax.swing.JCheckBox();
        s19 = new javax.swing.JCheckBox();
        s20 = new javax.swing.JCheckBox();
        s14 = new javax.swing.JCheckBox();
        s4 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel3.setText(" Working Days :");

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel4.setText("Select Student Name :");

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 1, 48)); // NOI18N
        jLabel1.setText("POWERPRO CALCULATOR");

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel2.setText("Attandance Calculator");

        c1.setBackground(new java.awt.Color(204, 204, 204));
        c1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "STUDENT NAME LIST :-", "Anivesh Samal", "Ashish Banerjee", "Tarun Panigrahi", "Tapan Ghadai", "Pinaki Nayak", "Tashmin mishra", "Sashikant das", "Archana panda", "Jaganath ratha", "Sujit panda", "Nibedita sahoo", "Minati pradhan", "Samir panda" }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        s1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        s1.setText("04/09/2023");

        s2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        s2.setText("05/09/2023");

        s3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        s3.setText("06/09/2023");

        s5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        s5.setText("08/09/2023");
        s5.setActionCommand("04/09/2023");

        s6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        s6.setText("11/09/2023");

        s7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        s7.setText("12/09/2023");

        s8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        s8.setText("13/09/2023");

        s9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        s9.setText("14/09/2023");

        s10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        s10.setText("15/09/2023");

        s11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        s11.setText("16/09/2023");

        s12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        s12.setText("18/09/2023");

        s13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        s13.setText("21/09/2023");

        s15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        s15.setText("25/09/2023");

        s16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        s16.setText("26/09/2023");

        s17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        s17.setText("27/09/2023");

        s18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        s18.setText("28/09/2023");
        s18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s18ActionPerformed(evt);
            }
        });

        s19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        s19.setText("29/09/2023");

        s20.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        s20.setText("30/09/2023");

        s14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        s14.setText("22/09/2023");

        s4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        s4.setText("07/09/2023");

        jButton1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        t1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton2.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jButton2.setText("EVALUATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jButton3.setText("<--PREVIOUS PAGE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jButton4.setText("EXIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel5.setText(" Attendance in percentage :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(229, 229, 229)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel4)
                                                .addComponent(c1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jButton1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jButton2)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(58, 58, 58)
                                                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(52, 52, 52)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(s13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(s12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(s11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(s10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(s9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(s8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(s7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(s6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(s5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(s3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(s2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(s1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(s14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(s15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(s16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(s17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(s18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(s19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(s20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(s4))
                                                .addGap(19, 19, 19)))))))
                        .addGap(0, 111, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(s1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s20)))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        float x = 0;
        if (c1.getSelectedItem().toString().equals("STUDENT NAME LIST :-"))
        {
            JOptionPane.showMessageDialog(this, "Please!,select a student name.");
        }
        else if (c1.getSelectedItem().toString().equals("Anivesh Samal")) {
        
        
            if (s1.isSelected() == false && s2.isSelected() == false && s3.isSelected() == false && s4.isSelected() == false && s5.isSelected() == false && s6.isSelected() == false && s7.isSelected() == false && s8.isSelected() == false && s9.isSelected() == false && s10.isSelected() == false && s11.isSelected() == false && s12.isSelected() == false && s13.isSelected() == false && s14.isSelected() == false && s15.isSelected() == false && s16.isSelected() == false && s17.isSelected() == false && s18.isSelected() == false && s19.isSelected() == false && s20.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "The student was not attended any classes");
      
            }
            if (s1.isSelected()) {
                x ++;
            }
            if (s1.isSelected()==false) {
                x = x +0;
            } 
             if (s2.isSelected()) {
                x ++;
            }
            if (s2.isSelected() == false) {
                x = x + 0;
            }
            if (s3.isSelected()) {
               x ++;
            }
            if (s3.isSelected() == false) {
                x = x + 0;
            }
            if (s4.isSelected()) {
                x ++;
            }
            if (s4.isSelected() == false) {
                x = x + 0;
            }
            if (s5.isSelected()) {
               x ++;
            }
            if (s5.isSelected() == false) {
                x = x + 0;
            }
            if (s6.isSelected()) {
               x ++;
            }
            if (s6.isSelected() == false) {
                x = x + 0;
            }
            if (s7.isSelected()) {
                x ++;
            }
            if (s7.isSelected() == false) {
                x = x + 0;
            }
            if (s8.isSelected()) {
                x ++;
            }
            if (s8.isSelected() == false) {
                x = x + 0;
            }
            if (s9.isSelected()) {
                x ++;
            }
            if (s9.isSelected() == false) {
                x = x + 0;
            }
            if (s10.isSelected()) {
               x ++;
            }
            if (s10.isSelected() == false) {
                x = x + 0;
            }
            if (s11.isSelected()) {
                x ++;
            }
            if (s11.isSelected() == false) {
                x = x + 0;
            }
             if (s12.isSelected()) {
               x ++;
            } 
             if (s12.isSelected() == false) {
                x = x + 0;
            }
             if (s13.isSelected()) {
                x ++;
            } 
             if (s13.isSelected() == false) {
                x = x + 0;
            }
            
            if (s14.isSelected()) {
                x ++;
            }
             if (s14.isSelected() == false) {
                x = x + 0;
            }
            if (s15.isSelected()) {
               x ++;
            }
             
             if (s15.isSelected() == false) {
                x = x + 0;
            }
            if (s16.isSelected()) {
                x ++;
            }
              if (s16.isSelected() == false) {
                x = x + 0;
            }
            if (s17.isSelected()) {
              x ++;
            }
             if (s17.isSelected() == false) {
                x = x + 0;
            }
            if (s18.isSelected()) {
              x ++;
            } 
            if (s18.isSelected() == false) {
                x = x + 0;
            } 
            if (s19.isSelected()) {
                 x ++;
            }
            if (s19.isSelected() == false) {
                x = x + 0;
            }
           if (s20.isSelected()) {
               x ++;
            }  
           if (s20.isSelected() == false) {
                x = x + 0;
            }
            
        
     
       
        }
        
         else if (c1.getSelectedItem().toString().equals("Ashish Banerjee")) {
        
        
            if (s1.isSelected() == false && s2.isSelected() == false && s3.isSelected() == false && s4.isSelected() == false && s5.isSelected() == false && s6.isSelected() == false && s7.isSelected() == false && s8.isSelected() == false && s9.isSelected() == false && s10.isSelected() == false && s11.isSelected() == false && s12.isSelected() == false && s13.isSelected() == false && s14.isSelected() == false && s15.isSelected() == false && s16.isSelected() == false && s17.isSelected() == false && s18.isSelected() == false && s19.isSelected() == false && s20.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "The student was not attended any classes");
      
            }
            if (s1.isSelected()) {
                x ++;
            }
            if (s1.isSelected()==false) {
                x = x +0;
            } 
             if (s2.isSelected()) {
                x ++;
            }
            if (s2.isSelected() == false) {
                x = x + 0;
            }
            if (s3.isSelected()) {
               x ++;
            }
            if (s3.isSelected() == false) {
                x = x + 0;
            }
            if (s4.isSelected()) {
                x ++;
            }
            if (s4.isSelected() == false) {
                x = x + 0;
            }
            if (s5.isSelected()) {
               x ++;
            }
            if (s5.isSelected() == false) {
                x = x + 0;
            }
            if (s6.isSelected()) {
               x ++;
            }
            if (s6.isSelected() == false) {
                x = x + 0;
            }
            if (s7.isSelected()) {
                x ++;
            }
            if (s7.isSelected() == false) {
                x = x + 0;
            }
            if (s8.isSelected()) {
                x ++;
            }
            if (s8.isSelected() == false) {
                x = x + 0;
            }
            if (s9.isSelected()) {
                x ++;
            }
            if (s9.isSelected() == false) {
                x = x + 0;
            }
            if (s10.isSelected()) {
               x ++;
            }
            if (s10.isSelected() == false) {
                x = x + 0;
            }
            if (s11.isSelected()) {
                x ++;
            }
            if (s11.isSelected() == false) {
                x = x + 0;
            }
             if (s12.isSelected()) {
               x ++;
            } 
             if (s12.isSelected() == false) {
                x = x + 0;
            }
             if (s13.isSelected()) {
                x ++;
            } 
             if (s13.isSelected() == false) {
                x = x + 0;
            }
            
            if (s14.isSelected()) {
                x ++;
            }
             if (s14.isSelected() == false) {
                x = x + 0;
            }
            if (s15.isSelected()) {
               x ++;
            }
             
             if (s15.isSelected() == false) {
                x = x + 0;
            }
            if (s16.isSelected()) {
                x ++;
            }
              if (s16.isSelected() == false) {
                x = x + 0;
            }
            if (s17.isSelected()) {
              x ++;
            }
             if (s17.isSelected() == false) {
                x = x + 0;
            }
            if (s18.isSelected()) {
              x ++;
            } 
            if (s18.isSelected() == false) {
                x = x + 0;
            } 
            if (s19.isSelected()) {
                 x ++;
            }
            if (s19.isSelected() == false) {
                x = x + 0;
            }
           if (s20.isSelected()) {
               x ++;
            }  
           if (s20.isSelected() == false) {
                x = x + 0;
            }
            
        
     
       
        }
         else if (c1.getSelectedItem().toString().equals("Tarun Panigrahi")) {
        
        
            if (s1.isSelected() == false && s2.isSelected() == false && s3.isSelected() == false && s4.isSelected() == false && s5.isSelected() == false && s6.isSelected() == false && s7.isSelected() == false && s8.isSelected() == false && s9.isSelected() == false && s10.isSelected() == false && s11.isSelected() == false && s12.isSelected() == false && s13.isSelected() == false && s14.isSelected() == false && s15.isSelected() == false && s16.isSelected() == false && s17.isSelected() == false && s18.isSelected() == false && s19.isSelected() == false && s20.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "The student was not attended any classes");
      
            }
            if (s1.isSelected()) {
                x ++;
            }
            if (s1.isSelected()==false) {
                x = x +0;
            } 
             if (s2.isSelected()) {
                x ++;
            }
            if (s2.isSelected() == false) {
                x = x + 0;
            }
            if (s3.isSelected()) {
               x ++;
            }
            if (s3.isSelected() == false) {
                x = x + 0;
            }
            if (s4.isSelected()) {
                x ++;
            }
            if (s4.isSelected() == false) {
                x = x + 0;
            }
            if (s5.isSelected()) {
               x ++;
            }
            if (s5.isSelected() == false) {
                x = x + 0;
            }
            if (s6.isSelected()) {
               x ++;
            }
            if (s6.isSelected() == false) {
                x = x + 0;
            }
            if (s7.isSelected()) {
                x ++;
            }
            if (s7.isSelected() == false) {
                x = x + 0;
            }
            if (s8.isSelected()) {
                x ++;
            }
            if (s8.isSelected() == false) {
                x = x + 0;
            }
            if (s9.isSelected()) {
                x ++;
            }
            if (s9.isSelected() == false) {
                x = x + 0;
            }
            if (s10.isSelected()) {
               x ++;
            }
            if (s10.isSelected() == false) {
                x = x + 0;
            }
            if (s11.isSelected()) {
                x ++;
            }
            if (s11.isSelected() == false) {
                x = x + 0;
            }
             if (s12.isSelected()) {
               x ++;
            } 
             if (s12.isSelected() == false) {
                x = x + 0;
            }
             if (s13.isSelected()) {
                x ++;
            } 
             if (s13.isSelected() == false) {
                x = x + 0;
            }
            
            if (s14.isSelected()) {
                x ++;
            }
             if (s14.isSelected() == false) {
                x = x + 0;
            }
            if (s15.isSelected()) {
               x ++;
            }
             
             if (s15.isSelected() == false) {
                x = x + 0;
            }
            if (s16.isSelected()) {
                x ++;
            }
              if (s16.isSelected() == false) {
                x = x + 0;
            }
            if (s17.isSelected()) {
              x ++;
            }
             if (s17.isSelected() == false) {
                x = x + 0;
            }
            if (s18.isSelected()) {
              x ++;
            } 
            if (s18.isSelected() == false) {
                x = x + 0;
            } 
            if (s19.isSelected()) {
                 x ++;
            }
            if (s19.isSelected() == false) {
                x = x + 0;
            }
           if (s20.isSelected()) {
               x ++;
            }  
           if (s20.isSelected() == false) {
                x = x + 0;
            }
            
        
     
       
        } else if (c1.getSelectedItem().toString().equals("Tapan Ghadai")) {
        
        
            if (s1.isSelected() == false && s2.isSelected() == false && s3.isSelected() == false && s4.isSelected() == false && s5.isSelected() == false && s6.isSelected() == false && s7.isSelected() == false && s8.isSelected() == false && s9.isSelected() == false && s10.isSelected() == false && s11.isSelected() == false && s12.isSelected() == false && s13.isSelected() == false && s14.isSelected() == false && s15.isSelected() == false && s16.isSelected() == false && s17.isSelected() == false && s18.isSelected() == false && s19.isSelected() == false && s20.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "The student was not attended any classes");
      
            }
            if (s1.isSelected()) {
                x ++;
            }
            if (s1.isSelected()==false) {
                x = x +0;
            } 
             if (s2.isSelected()) {
                x ++;
            }
            if (s2.isSelected() == false) {
                x = x + 0;
            }
            if (s3.isSelected()) {
               x ++;
            }
            if (s3.isSelected() == false) {
                x = x + 0;
            }
            if (s4.isSelected()) {
                x ++;
            }
            if (s4.isSelected() == false) {
                x = x + 0;
            }
            if (s5.isSelected()) {
               x ++;
            }
            if (s5.isSelected() == false) {
                x = x + 0;
            }
            if (s6.isSelected()) {
               x ++;
            }
            if (s6.isSelected() == false) {
                x = x + 0;
            }
            if (s7.isSelected()) {
                x ++;
            }
            if (s7.isSelected() == false) {
                x = x + 0;
            }
            if (s8.isSelected()) {
                x ++;
            }
            if (s8.isSelected() == false) {
                x = x + 0;
            }
            if (s9.isSelected()) {
                x ++;
            }
            if (s9.isSelected() == false) {
                x = x + 0;
            }
            if (s10.isSelected()) {
               x ++;
            }
            if (s10.isSelected() == false) {
                x = x + 0;
            }
            if (s11.isSelected()) {
                x ++;
            }
            if (s11.isSelected() == false) {
                x = x + 0;
            }
             if (s12.isSelected()) {
               x ++;
            } 
             if (s12.isSelected() == false) {
                x = x + 0;
            }
             if (s13.isSelected()) {
                x ++;
            } 
             if (s13.isSelected() == false) {
                x = x + 0;
            }
            
            if (s14.isSelected()) {
                x ++;
            }
             if (s14.isSelected() == false) {
                x = x + 0;
            }
            if (s15.isSelected()) {
               x ++;
            }
             
             if (s15.isSelected() == false) {
                x = x + 0;
            }
            if (s16.isSelected()) {
                x ++;
            }
              if (s16.isSelected() == false) {
                x = x + 0;
            }
            if (s17.isSelected()) {
              x ++;
            }
             if (s17.isSelected() == false) {
                x = x + 0;
            }
            if (s18.isSelected()) {
              x ++;
            } 
            if (s18.isSelected() == false) {
                x = x + 0;
            } 
            if (s19.isSelected()) {
                 x ++;
            }
            if (s19.isSelected() == false) {
                x = x + 0;
            }
           if (s20.isSelected()) {
               x ++;
            }  
           if (s20.isSelected() == false) {
                x = x + 0;
            }
            
        
     
       
        } else if (c1.getSelectedItem().toString().equals("Pinaki Nayak")) {
        
        
            if (s1.isSelected() == false && s2.isSelected() == false && s3.isSelected() == false && s4.isSelected() == false && s5.isSelected() == false && s6.isSelected() == false && s7.isSelected() == false && s8.isSelected() == false && s9.isSelected() == false && s10.isSelected() == false && s11.isSelected() == false && s12.isSelected() == false && s13.isSelected() == false && s14.isSelected() == false && s15.isSelected() == false && s16.isSelected() == false && s17.isSelected() == false && s18.isSelected() == false && s19.isSelected() == false && s20.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "The student was not attended any classes");
      
            }
            if (s1.isSelected()) {
                x ++;
            }
            if (s1.isSelected()==false) {
                x = x +0;
            } 
             if (s2.isSelected()) {
                x ++;
            }
            if (s2.isSelected() == false) {
                x = x + 0;
            }
            if (s3.isSelected()) {
               x ++;
            }
            if (s3.isSelected() == false) {
                x = x + 0;
            }
            if (s4.isSelected()) {
                x ++;
            }
            if (s4.isSelected() == false) {
                x = x + 0;
            }
            if (s5.isSelected()) {
               x ++;
            }
            if (s5.isSelected() == false) {
                x = x + 0;
            }
            if (s6.isSelected()) {
               x ++;
            }
            if (s6.isSelected() == false) {
                x = x + 0;
            }
            if (s7.isSelected()) {
                x ++;
            }
            if (s7.isSelected() == false) {
                x = x + 0;
            }
            if (s8.isSelected()) {
                x ++;
            }
            if (s8.isSelected() == false) {
                x = x + 0;
            }
            if (s9.isSelected()) {
                x ++;
            }
            if (s9.isSelected() == false) {
                x = x + 0;
            }
            if (s10.isSelected()) {
               x ++;
            }
            if (s10.isSelected() == false) {
                x = x + 0;
            }
            if (s11.isSelected()) {
                x ++;
            }
            if (s11.isSelected() == false) {
                x = x + 0;
            }
             if (s12.isSelected()) {
               x ++;
            } 
             if (s12.isSelected() == false) {
                x = x + 0;
            }
             if (s13.isSelected()) {
                x ++;
            } 
             if (s13.isSelected() == false) {
                x = x + 0;
            }
            
            if (s14.isSelected()) {
                x ++;
            }
             if (s14.isSelected() == false) {
                x = x + 0;
            }
            if (s15.isSelected()) {
               x ++;
            }
             
             if (s15.isSelected() == false) {
                x = x + 0;
            }
            if (s16.isSelected()) {
                x ++;
            }
              if (s16.isSelected() == false) {
                x = x + 0;
            }
            if (s17.isSelected()) {
              x ++;
            }
             if (s17.isSelected() == false) {
                x = x + 0;
            }
            if (s18.isSelected()) {
              x ++;
            } 
            if (s18.isSelected() == false) {
                x = x + 0;
            } 
            if (s19.isSelected()) {
                 x ++;
            }
            if (s19.isSelected() == false) {
                x = x + 0;
            }
           if (s20.isSelected()) {
               x ++;
            }  
           if (s20.isSelected() == false) {
                x = x + 0;
            }
            
        
     
       
        } else if (c1.getSelectedItem().toString().equals("Tashmin mishra")) {
        
        
            if (s1.isSelected() == false && s2.isSelected() == false && s3.isSelected() == false && s4.isSelected() == false && s5.isSelected() == false && s6.isSelected() == false && s7.isSelected() == false && s8.isSelected() == false && s9.isSelected() == false && s10.isSelected() == false && s11.isSelected() == false && s12.isSelected() == false && s13.isSelected() == false && s14.isSelected() == false && s15.isSelected() == false && s16.isSelected() == false && s17.isSelected() == false && s18.isSelected() == false && s19.isSelected() == false && s20.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "The student was not attended any classes");
      
            }
            if (s1.isSelected()) {
                x ++;
            }
            if (s1.isSelected()==false) {
                x = x +0;
            } 
             if (s2.isSelected()) {
                x ++;
            }
            if (s2.isSelected() == false) {
                x = x + 0;
            }
            if (s3.isSelected()) {
               x ++;
            }
            if (s3.isSelected() == false) {
                x = x + 0;
            }
            if (s4.isSelected()) {
                x ++;
            }
            if (s4.isSelected() == false) {
                x = x + 0;
            }
            if (s5.isSelected()) {
               x ++;
            }
            if (s5.isSelected() == false) {
                x = x + 0;
            }
            if (s6.isSelected()) {
               x ++;
            }
            if (s6.isSelected() == false) {
                x = x + 0;
            }
            if (s7.isSelected()) {
                x ++;
            }
            if (s7.isSelected() == false) {
                x = x + 0;
            }
            if (s8.isSelected()) {
                x ++;
            }
            if (s8.isSelected() == false) {
                x = x + 0;
            }
            if (s9.isSelected()) {
                x ++;
            }
            if (s9.isSelected() == false) {
                x = x + 0;
            }
            if (s10.isSelected()) {
               x ++;
            }
            if (s10.isSelected() == false) {
                x = x + 0;
            }
            if (s11.isSelected()) {
                x ++;
            }
            if (s11.isSelected() == false) {
                x = x + 0;
            }
             if (s12.isSelected()) {
               x ++;
            } 
             if (s12.isSelected() == false) {
                x = x + 0;
            }
             if (s13.isSelected()) {
                x ++;
            } 
             if (s13.isSelected() == false) {
                x = x + 0;
            }
            
            if (s14.isSelected()) {
                x ++;
            }
             if (s14.isSelected() == false) {
                x = x + 0;
            }
            if (s15.isSelected()) {
               x ++;
            }
             
             if (s15.isSelected() == false) {
                x = x + 0;
            }
            if (s16.isSelected()) {
                x ++;
            }
              if (s16.isSelected() == false) {
                x = x + 0;
            }
            if (s17.isSelected()) {
              x ++;
            }
             if (s17.isSelected() == false) {
                x = x + 0;
            }
            if (s18.isSelected()) {
              x ++;
            } 
            if (s18.isSelected() == false) {
                x = x + 0;
            } 
            if (s19.isSelected()) {
                 x ++;
            }
            if (s19.isSelected() == false) {
                x = x + 0;
            }
           if (s20.isSelected()) {
               x ++;
            }  
           if (s20.isSelected() == false) {
                x = x + 0;
            }
            
        
     
       
        } else if (c1.getSelectedItem().toString().equals("Sashikant das")) {
        
        
            if (s1.isSelected() == false && s2.isSelected() == false && s3.isSelected() == false && s4.isSelected() == false && s5.isSelected() == false && s6.isSelected() == false && s7.isSelected() == false && s8.isSelected() == false && s9.isSelected() == false && s10.isSelected() == false && s11.isSelected() == false && s12.isSelected() == false && s13.isSelected() == false && s14.isSelected() == false && s15.isSelected() == false && s16.isSelected() == false && s17.isSelected() == false && s18.isSelected() == false && s19.isSelected() == false && s20.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "The student was not attended any classes");
      
            }
            if (s1.isSelected()) {
                x ++;
            }
            if (s1.isSelected()==false) {
                x = x +0;
            } 
             if (s2.isSelected()) {
                x ++;
            }
            if (s2.isSelected() == false) {
                x = x + 0;
            }
            if (s3.isSelected()) {
               x ++;
            }
            if (s3.isSelected() == false) {
                x = x + 0;
            }
            if (s4.isSelected()) {
                x ++;
            }
            if (s4.isSelected() == false) {
                x = x + 0;
            }
            if (s5.isSelected()) {
               x ++;
            }
            if (s5.isSelected() == false) {
                x = x + 0;
            }
            if (s6.isSelected()) {
               x ++;
            }
            if (s6.isSelected() == false) {
                x = x + 0;
            }
            if (s7.isSelected()) {
                x ++;
            }
            if (s7.isSelected() == false) {
                x = x + 0;
            }
            if (s8.isSelected()) {
                x ++;
            }
            if (s8.isSelected() == false) {
                x = x + 0;
            }
            if (s9.isSelected()) {
                x ++;
            }
            if (s9.isSelected() == false) {
                x = x + 0;
            }
            if (s10.isSelected()) {
               x ++;
            }
            if (s10.isSelected() == false) {
                x = x + 0;
            }
            if (s11.isSelected()) {
                x ++;
            }
            if (s11.isSelected() == false) {
                x = x + 0;
            }
             if (s12.isSelected()) {
               x ++;
            } 
             if (s12.isSelected() == false) {
                x = x + 0;
            }
             if (s13.isSelected()) {
                x ++;
            } 
             if (s13.isSelected() == false) {
                x = x + 0;
            }
            
            if (s14.isSelected()) {
                x ++;
            }
             if (s14.isSelected() == false) {
                x = x + 0;
            }
            if (s15.isSelected()) {
               x ++;
            }
             
             if (s15.isSelected() == false) {
                x = x + 0;
            }
            if (s16.isSelected()) {
                x ++;
            }
              if (s16.isSelected() == false) {
                x = x + 0;
            }
            if (s17.isSelected()) {
              x ++;
            }
             if (s17.isSelected() == false) {
                x = x + 0;
            }
            if (s18.isSelected()) {
              x ++;
            } 
            if (s18.isSelected() == false) {
                x = x + 0;
            } 
            if (s19.isSelected()) {
                 x ++;
            }
            if (s19.isSelected() == false) {
                x = x + 0;
            }
           if (s20.isSelected()) {
               x ++;
            }  
           if (s20.isSelected() == false) {
                x = x + 0;
            }
            
        
     
       
        } else if (c1.getSelectedItem().toString().equals("Archana panda")) {
        
        
            if (s1.isSelected() == false && s2.isSelected() == false && s3.isSelected() == false && s4.isSelected() == false && s5.isSelected() == false && s6.isSelected() == false && s7.isSelected() == false && s8.isSelected() == false && s9.isSelected() == false && s10.isSelected() == false && s11.isSelected() == false && s12.isSelected() == false && s13.isSelected() == false && s14.isSelected() == false && s15.isSelected() == false && s16.isSelected() == false && s17.isSelected() == false && s18.isSelected() == false && s19.isSelected() == false && s20.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "The student was not attended any classes");
      
            }
            if (s1.isSelected()) {
                x ++;
            }
            if (s1.isSelected()==false) {
                x = x +0;
            } 
             if (s2.isSelected()) {
                x ++;
            }
            if (s2.isSelected() == false) {
                x = x + 0;
            }
            if (s3.isSelected()) {
               x ++;
            }
            if (s3.isSelected() == false) {
                x = x + 0;
            }
            if (s4.isSelected()) {
                x ++;
            }
            if (s4.isSelected() == false) {
                x = x + 0;
            }
            if (s5.isSelected()) {
               x ++;
            }
            if (s5.isSelected() == false) {
                x = x + 0;
            }
            if (s6.isSelected()) {
               x ++;
            }
            if (s6.isSelected() == false) {
                x = x + 0;
            }
            if (s7.isSelected()) {
                x ++;
            }
            if (s7.isSelected() == false) {
                x = x + 0;
            }
            if (s8.isSelected()) {
                x ++;
            }
            if (s8.isSelected() == false) {
                x = x + 0;
            }
            if (s9.isSelected()) {
                x ++;
            }
            if (s9.isSelected() == false) {
                x = x + 0;
            }
            if (s10.isSelected()) {
               x ++;
            }
            if (s10.isSelected() == false) {
                x = x + 0;
            }
            if (s11.isSelected()) {
                x ++;
            }
            if (s11.isSelected() == false) {
                x = x + 0;
            }
             if (s12.isSelected()) {
               x ++;
            } 
             if (s12.isSelected() == false) {
                x = x + 0;
            }
             if (s13.isSelected()) {
                x ++;
            } 
             if (s13.isSelected() == false) {
                x = x + 0;
            }
            
            if (s14.isSelected()) {
                x ++;
            }
             if (s14.isSelected() == false) {
                x = x + 0;
            }
            if (s15.isSelected()) {
               x ++;
            }
             
             if (s15.isSelected() == false) {
                x = x + 0;
            }
            if (s16.isSelected()) {
                x ++;
            }
              if (s16.isSelected() == false) {
                x = x + 0;
            }
            if (s17.isSelected()) {
              x ++;
            }
             if (s17.isSelected() == false) {
                x = x + 0;
            }
            if (s18.isSelected()) {
              x ++;
            } 
            if (s18.isSelected() == false) {
                x = x + 0;
            } 
            if (s19.isSelected()) {
                 x ++;
            }
            if (s19.isSelected() == false) {
                x = x + 0;
            }
           if (s20.isSelected()) {
               x ++;
            }  
           if (s20.isSelected() == false) {
                x = x + 0;
            }
            
        
     
       
        } else if (c1.getSelectedItem().toString().equals("Jaganath ratha")) {
        
        
            if (s1.isSelected() == false && s2.isSelected() == false && s3.isSelected() == false && s4.isSelected() == false && s5.isSelected() == false && s6.isSelected() == false && s7.isSelected() == false && s8.isSelected() == false && s9.isSelected() == false && s10.isSelected() == false && s11.isSelected() == false && s12.isSelected() == false && s13.isSelected() == false && s14.isSelected() == false && s15.isSelected() == false && s16.isSelected() == false && s17.isSelected() == false && s18.isSelected() == false && s19.isSelected() == false && s20.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "The student was not attended any classes");
      
            }
            if (s1.isSelected()) {
                x ++;
            }
            if (s1.isSelected()==false) {
                x = x +0;
            } 
             if (s2.isSelected()) {
                x ++;
            }
            if (s2.isSelected() == false) {
                x = x + 0;
            }
            if (s3.isSelected()) {
               x ++;
            }
            if (s3.isSelected() == false) {
                x = x + 0;
            }
            if (s4.isSelected()) {
                x ++;
            }
            if (s4.isSelected() == false) {
                x = x + 0;
            }
            if (s5.isSelected()) {
               x ++;
            }
            if (s5.isSelected() == false) {
                x = x + 0;
            }
            if (s6.isSelected()) {
               x ++;
            }
            if (s6.isSelected() == false) {
                x = x + 0;
            }
            if (s7.isSelected()) {
                x ++;
            }
            if (s7.isSelected() == false) {
                x = x + 0;
            }
            if (s8.isSelected()) {
                x ++;
            }
            if (s8.isSelected() == false) {
                x = x + 0;
            }
            if (s9.isSelected()) {
                x ++;
            }
            if (s9.isSelected() == false) {
                x = x + 0;
            }
            if (s10.isSelected()) {
               x ++;
            }
            if (s10.isSelected() == false) {
                x = x + 0;
            }
            if (s11.isSelected()) {
                x ++;
            }
            if (s11.isSelected() == false) {
                x = x + 0;
            }
             if (s12.isSelected()) {
               x ++;
            } 
             if (s12.isSelected() == false) {
                x = x + 0;
            }
             if (s13.isSelected()) {
                x ++;
            } 
             if (s13.isSelected() == false) {
                x = x + 0;
            }
            
            if (s14.isSelected()) {
                x ++;
            }
             if (s14.isSelected() == false) {
                x = x + 0;
            }
            if (s15.isSelected()) {
               x ++;
            }
             
             if (s15.isSelected() == false) {
                x = x + 0;
            }
            if (s16.isSelected()) {
                x ++;
            }
              if (s16.isSelected() == false) {
                x = x + 0;
            }
            if (s17.isSelected()) {
              x ++;
            }
             if (s17.isSelected() == false) {
                x = x + 0;
            }
            if (s18.isSelected()) {
              x ++;
            } 
            if (s18.isSelected() == false) {
                x = x + 0;
            } 
            if (s19.isSelected()) {
                 x ++;
            }
            if (s19.isSelected() == false) {
                x = x + 0;
            }
           if (s20.isSelected()) {
               x ++;
            }  
           if (s20.isSelected() == false) {
                x = x + 0;
            }
            
        
     
       
        } else if (c1.getSelectedItem().toString().equals("Sujit panda")) {
        
        
            if (s1.isSelected() == false && s2.isSelected() == false && s3.isSelected() == false && s4.isSelected() == false && s5.isSelected() == false && s6.isSelected() == false && s7.isSelected() == false && s8.isSelected() == false && s9.isSelected() == false && s10.isSelected() == false && s11.isSelected() == false && s12.isSelected() == false && s13.isSelected() == false && s14.isSelected() == false && s15.isSelected() == false && s16.isSelected() == false && s17.isSelected() == false && s18.isSelected() == false && s19.isSelected() == false && s20.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "The student was not attended any classes");
      
            }
            if (s1.isSelected()) {
                x ++;
            }
            if (s1.isSelected()==false) {
                x = x +0;
            } 
             if (s2.isSelected()) {
                x ++;
            }
            if (s2.isSelected() == false) {
                x = x + 0;
            }
            if (s3.isSelected()) {
               x ++;
            }
            if (s3.isSelected() == false) {
                x = x + 0;
            }
            if (s4.isSelected()) {
                x ++;
            }
            if (s4.isSelected() == false) {
                x = x + 0;
            }
            if (s5.isSelected()) {
               x ++;
            }
            if (s5.isSelected() == false) {
                x = x + 0;
            }
            if (s6.isSelected()) {
               x ++;
            }
            if (s6.isSelected() == false) {
                x = x + 0;
            }
            if (s7.isSelected()) {
                x ++;
            }
            if (s7.isSelected() == false) {
                x = x + 0;
            }
            if (s8.isSelected()) {
                x ++;
            }
            if (s8.isSelected() == false) {
                x = x + 0;
            }
            if (s9.isSelected()) {
                x ++;
            }
            if (s9.isSelected() == false) {
                x = x + 0;
            }
            if (s10.isSelected()) {
               x ++;
            }
            if (s10.isSelected() == false) {
                x = x + 0;
            }
            if (s11.isSelected()) {
                x ++;
            }
            if (s11.isSelected() == false) {
                x = x + 0;
            }
             if (s12.isSelected()) {
               x ++;
            } 
             if (s12.isSelected() == false) {
                x = x + 0;
            }
             if (s13.isSelected()) {
                x ++;
            } 
             if (s13.isSelected() == false) {
                x = x + 0;
            }
            
            if (s14.isSelected()) {
                x ++;
            }
             if (s14.isSelected() == false) {
                x = x + 0;
            }
            if (s15.isSelected()) {
               x ++;
            }
             
             if (s15.isSelected() == false) {
                x = x + 0;
            }
            if (s16.isSelected()) {
                x ++;
            }
              if (s16.isSelected() == false) {
                x = x + 0;
            }
            if (s17.isSelected()) {
              x ++;
            }
             if (s17.isSelected() == false) {
                x = x + 0;
            }
            if (s18.isSelected()) {
              x ++;
            } 
            if (s18.isSelected() == false) {
                x = x + 0;
            } 
            if (s19.isSelected()) {
                 x ++;
            }
            if (s19.isSelected() == false) {
                x = x + 0;
            }
           if (s20.isSelected()) {
               x ++;
            }  
           if (s20.isSelected() == false) {
                x = x + 0;
            }
            
        
     
       
        } else if (c1.getSelectedItem().toString().equals("Nibedita sahoo")) {
        
        
            if (s1.isSelected() == false && s2.isSelected() == false && s3.isSelected() == false && s4.isSelected() == false && s5.isSelected() == false && s6.isSelected() == false && s7.isSelected() == false && s8.isSelected() == false && s9.isSelected() == false && s10.isSelected() == false && s11.isSelected() == false && s12.isSelected() == false && s13.isSelected() == false && s14.isSelected() == false && s15.isSelected() == false && s16.isSelected() == false && s17.isSelected() == false && s18.isSelected() == false && s19.isSelected() == false && s20.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "The student was not attended any classes");
      
            }
            if (s1.isSelected()) {
                x ++;
            }
            if (s1.isSelected()==false) {
                x = x +0;
            } 
             if (s2.isSelected()) {
                x ++;
            }
            if (s2.isSelected() == false) {
                x = x + 0;
            }
            if (s3.isSelected()) {
               x ++;
            }
            if (s3.isSelected() == false) {
                x = x + 0;
            }
            if (s4.isSelected()) {
                x ++;
            }
            if (s4.isSelected() == false) {
                x = x + 0;
            }
            if (s5.isSelected()) {
               x ++;
            }
            if (s5.isSelected() == false) {
                x = x + 0;
            }
            if (s6.isSelected()) {
               x ++;
            }
            if (s6.isSelected() == false) {
                x = x + 0;
            }
            if (s7.isSelected()) {
                x ++;
            }
            if (s7.isSelected() == false) {
                x = x + 0;
            }
            if (s8.isSelected()) {
                x ++;
            }
            if (s8.isSelected() == false) {
                x = x + 0;
            }
            if (s9.isSelected()) {
                x ++;
            }
            if (s9.isSelected() == false) {
                x = x + 0;
            }
            if (s10.isSelected()) {
               x ++;
            }
            if (s10.isSelected() == false) {
                x = x + 0;
            }
            if (s11.isSelected()) {
                x ++;
            }
            if (s11.isSelected() == false) {
                x = x + 0;
            }
             if (s12.isSelected()) {
               x ++;
            } 
             if (s12.isSelected() == false) {
                x = x + 0;
            }
             if (s13.isSelected()) {
                x ++;
            } 
             if (s13.isSelected() == false) {
                x = x + 0;
            }
            
            if (s14.isSelected()) {
                x ++;
            }
             if (s14.isSelected() == false) {
                x = x + 0;
            }
            if (s15.isSelected()) {
               x ++;
            }
             
             if (s15.isSelected() == false) {
                x = x + 0;
            }
            if (s16.isSelected()) {
                x ++;
            }
              if (s16.isSelected() == false) {
                x = x + 0;
            }
            if (s17.isSelected()) {
              x ++;
            }
             if (s17.isSelected() == false) {
                x = x + 0;
            }
            if (s18.isSelected()) {
              x ++;
            } 
            if (s18.isSelected() == false) {
                x = x + 0;
            } 
            if (s19.isSelected()) {
                 x ++;
            }
            if (s19.isSelected() == false) {
                x = x + 0;
            }
           if (s20.isSelected()) {
               x ++;
            }  
           if (s20.isSelected() == false) {
                x = x + 0;
            }
            
        
     
       
        } else if (c1.getSelectedItem().toString().equals("Minati pradhan")) {
        
        
            if (s1.isSelected() == false && s2.isSelected() == false && s3.isSelected() == false && s4.isSelected() == false && s5.isSelected() == false && s6.isSelected() == false && s7.isSelected() == false && s8.isSelected() == false && s9.isSelected() == false && s10.isSelected() == false && s11.isSelected() == false && s12.isSelected() == false && s13.isSelected() == false && s14.isSelected() == false && s15.isSelected() == false && s16.isSelected() == false && s17.isSelected() == false && s18.isSelected() == false && s19.isSelected() == false && s20.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "The student was not attended any classes");
      
            }
            if (s1.isSelected()) {
                x ++;
            }
            if (s1.isSelected()==false) {
                x = x +0;
            } 
             if (s2.isSelected()) {
                x ++;
            }
            if (s2.isSelected() == false) {
                x = x + 0;
            }
            if (s3.isSelected()) {
               x ++;
            }
            if (s3.isSelected() == false) {
                x = x + 0;
            }
            if (s4.isSelected()) {
                x ++;
            }
            if (s4.isSelected() == false) {
                x = x + 0;
            }
            if (s5.isSelected()) {
               x ++;
            }
            if (s5.isSelected() == false) {
                x = x + 0;
            }
            if (s6.isSelected()) {
               x ++;
            }
            if (s6.isSelected() == false) {
                x = x + 0;
            }
            if (s7.isSelected()) {
                x ++;
            }
            if (s7.isSelected() == false) {
                x = x + 0;
            }
            if (s8.isSelected()) {
                x ++;
            }
            if (s8.isSelected() == false) {
                x = x + 0;
            }
            if (s9.isSelected()) {
                x ++;
            }
            if (s9.isSelected() == false) {
                x = x + 0;
            }
            if (s10.isSelected()) {
               x ++;
            }
            if (s10.isSelected() == false) {
                x = x + 0;
            }
            if (s11.isSelected()) {
                x ++;
            }
            if (s11.isSelected() == false) {
                x = x + 0;
            }
             if (s12.isSelected()) {
               x ++;
            } 
             if (s12.isSelected() == false) {
                x = x + 0;
            }
             if (s13.isSelected()) {
                x ++;
            } 
             if (s13.isSelected() == false) {
                x = x + 0;
            }
            
            if (s14.isSelected()) {
                x ++;
            }
             if (s14.isSelected() == false) {
                x = x + 0;
            }
            if (s15.isSelected()) {
               x ++;
            }
             
             if (s15.isSelected() == false) {
                x = x + 0;
            }
            if (s16.isSelected()) {
                x ++;
            }
              if (s16.isSelected() == false) {
                x = x + 0;
            }
            if (s17.isSelected()) {
              x ++;
            }
             if (s17.isSelected() == false) {
                x = x + 0;
            }
            if (s18.isSelected()) {
              x ++;
            } 
            if (s18.isSelected() == false) {
                x = x + 0;
            } 
            if (s19.isSelected()) {
                 x ++;
            }
            if (s19.isSelected() == false) {
                x = x + 0;
            }
           if (s20.isSelected()) {
               x ++;
            }  
           if (s20.isSelected() == false) {
                x = x + 0;
            }
            
        
     
       
        } else if (c1.getSelectedItem().toString().equals("Samir panda")) {
        
        
            if (s1.isSelected() == false && s2.isSelected() == false && s3.isSelected() == false && s4.isSelected() == false && s5.isSelected() == false && s6.isSelected() == false && s7.isSelected() == false && s8.isSelected() == false && s9.isSelected() == false && s10.isSelected() == false && s11.isSelected() == false && s12.isSelected() == false && s13.isSelected() == false && s14.isSelected() == false && s15.isSelected() == false && s16.isSelected() == false && s17.isSelected() == false && s18.isSelected() == false && s19.isSelected() == false && s20.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "The student was not attended any classes");
      
            }
            if (s1.isSelected()) {
                x ++;
            }
            if (s1.isSelected()==false) {
                x = x +0;
            } 
             if (s2.isSelected()) {
                x ++;
            }
            if (s2.isSelected() == false) {
                x = x + 0;
            }
            if (s3.isSelected()) {
               x ++;
            }
            if (s3.isSelected() == false) {
                x = x + 0;
            }
            if (s4.isSelected()) {
                x ++;
            }
            if (s4.isSelected() == false) {
                x = x + 0;
            }
            if (s5.isSelected()) {
               x ++;
            }
            if (s5.isSelected() == false) {
                x = x + 0;
            }
            if (s6.isSelected()) {
               x ++;
            }
            if (s6.isSelected() == false) {
                x = x + 0;
            }
            if (s7.isSelected()) {
                x ++;
            }
            if (s7.isSelected() == false) {
                x = x + 0;
            }
            if (s8.isSelected()) {
                x ++;
            }
            if (s8.isSelected() == false) {
                x = x + 0;
            }
            if (s9.isSelected()) {
                x ++;
            }
            if (s9.isSelected() == false) {
                x = x + 0;
            }
            if (s10.isSelected()) {
               x ++;
            }
            if (s10.isSelected() == false) {
                x = x + 0;
            }
            if (s11.isSelected()) {
                x ++;
            }
            if (s11.isSelected() == false) {
                x = x + 0;
            }
             if (s12.isSelected()) {
               x ++;
            } 
             if (s12.isSelected() == false) {
                x = x + 0;
            }
             if (s13.isSelected()) {
                x ++;
            } 
             if (s13.isSelected() == false) {
                x = x + 0;
            }
            
            if (s14.isSelected()) {
                x ++;
            }
             if (s14.isSelected() == false) {
                x = x + 0;
            }
            if (s15.isSelected()) {
               x ++;
            }
             
             if (s15.isSelected() == false) {
                x = x + 0;
            }
            if (s16.isSelected()) {
                x ++;
            }
              if (s16.isSelected() == false) {
                x = x + 0;
            }
            if (s17.isSelected()) {
              x ++;
            }
             if (s17.isSelected() == false) {
                x = x + 0;
            }
            if (s18.isSelected()) {
              x ++;
            } 
            if (s18.isSelected() == false) {
                x = x + 0;
            } 
            if (s19.isSelected()) {
                 x ++;
            }
            if (s19.isSelected() == false) {
                x = x + 0;
            }
           if (s20.isSelected()) {
               x ++;
            }  
           if (s20.isSelected() == false) {
                x = x + 0;
            }
      
        }
      
        
         float p =(x/20)*100;
         double f = Math.round(p*100)/100.0;
         t1.setText(f+"%");
     
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        c1.setSelectedItem("STUDENT NAME LIST :-");
        s1.setSelected(false);
        s2.setSelected(false);
        s3.setSelected(false);
        s4.setSelected(false);
        s5.setSelected(false);
        s6.setSelected(false);
        s7.setSelected(false);
        s8.setSelected(false);
        s9.setSelected(false);
        s10.setSelected(false);
        s11.setSelected(false);
        s12.setSelected(false);
        s13.setSelected(false);
        s14.setSelected(false);
        s15.setSelected(false);
        s16.setSelected(false);
        s17.setSelected(false);
        s18.setSelected(false);
        s19.setSelected(false);
        s20.setSelected(false);
        t1.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

System.exit(0);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void s18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s18ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    ChoosePage cp = new ChoosePage();
    cp.setVisible(true);
    this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttandanceCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttandanceCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttandanceCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttandanceCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AttandanceCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox s1;
    private javax.swing.JCheckBox s10;
    private javax.swing.JCheckBox s11;
    private javax.swing.JCheckBox s12;
    private javax.swing.JCheckBox s13;
    private javax.swing.JCheckBox s14;
    private javax.swing.JCheckBox s15;
    private javax.swing.JCheckBox s16;
    private javax.swing.JCheckBox s17;
    private javax.swing.JCheckBox s18;
    private javax.swing.JCheckBox s19;
    private javax.swing.JCheckBox s2;
    private javax.swing.JCheckBox s20;
    private javax.swing.JCheckBox s3;
    private javax.swing.JCheckBox s4;
    private javax.swing.JCheckBox s5;
    private javax.swing.JCheckBox s6;
    private javax.swing.JCheckBox s7;
    private javax.swing.JCheckBox s8;
    private javax.swing.JCheckBox s9;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
